name: admin_dashboard
description: A Flutter admin dashboard application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  get_it: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/font/DM_Sans/DMSans-Bold.ttf
        - asset: assets/font/DM_Sans/DMSans-BoldItalic.ttf
        - asset: assets/font/DM_Sans/DMSans-Italic.ttf
        - asset: assets/font/DM_Sans/DMSans-Medium.ttf
        - asset: assets/font/DM_Sans/DMSans-MediumItalic.ttf
        - asset: assets/font/DM_Sans/DMSans-Regular.ttf
